on: [ push, pull_request ]

name: Build and Test

jobs:
  build_and_test:
    name: Build & Test and Check Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: --release --all-features
      - uses: actions-rs/cargo@v1
        name: Test
        with:
          command: test
          args: --release --all-features
      - uses: actions-rs/cargo@v1
        name: Check Code Style with fmt
        with:
          command: fmt
          args: --all -- --check
